# Generated by Django 5.1.6 on 2025-02-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_escala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escala',
            old_name='perticipantes',
            new_name='participante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mininsterio',
        ),
    ]
