# Generated by Django 5.1.6 on 2025-02-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_perticipantes_escala_participante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='instrumento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
