# Generated by Django 5.1.6 on 2025-02-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_instrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='instrumento',
            field=models.CharField(blank=True, choices=[('1', 'Bateria'), ('2', 'Guitarra'), ('3', 'Vocal')], max_length=50, null=True),
        ),
    ]
