# Generated by Django 5.1.6 on 2025-03-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuario_instrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='instrumento',
            field=models.CharField(blank=True, choices=[('1', 'Bateria'), ('2', 'Guitarra'), ('3', 'Vocal'), ('4', 'Teclado'), ('5', 'Baixo'), ('6', 'Violao')], max_length=50, null=True),
        ),
    ]
