# Generated by Django 5.1.7 on 2025-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='instrumento',
            new_name='atuacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fisrt_funcao',
            field=models.CharField(blank=True, choices=[('1', 'Louvor'), ('2', 'Midia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='secund_funcao',
            field=models.CharField(blank=True, choices=[('1', 'Louvor'), ('2', 'Midia')], max_length=50, null=True),
        ),
    ]
