# Generated by Django 5.1.7 on 2025-03-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_usuario_fisrt_funcao_usuario_first_funcao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='first_funcao',
            new_name='funcao_1',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='secund_funcao',
            new_name='funcao_2',
        ),
    ]
