# Generated by Django 5.1.7 on 2025-03-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_first_funcao_usuario_funcao_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
