# Generated by Django 5.1.7 on 2025-03-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usuario_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
