# Generated by Django 5.1.7 on 2025-03-11 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_birth_date_usuario_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='funcao',
            field=models.CharField(blank=True, choices=[('1', 'Cantor'), ('2', 'Tecladista'), ('3', 'Sonoplasta')], max_length=10, null=True, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(through='core.Escala', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='escala',
            name='participante',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='atuacao',
            field=models.CharField(blank=True, choices=[('1', 'Louvor'), ('2', 'Midia'), ('3', 'Midia e Louvor')], max_length=50, null=True, verbose_name='Atuação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao_1',
            field=models.CharField(blank=True, choices=[('1', 'Bateria'), ('2', 'Guitarra'), ('3', 'Vocal'), ('4', 'Teclado'), ('5', 'Baixo'), ('6', 'Violao'), ('7', 'Som'), ('8', 'Projetor'), ('9', 'Fotofilm'), ('10', 'Live'), ('11', 'Total Midia')], max_length=50, null=True, verbose_name='1ª Função'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao_2',
            field=models.CharField(blank=True, choices=[('1', 'Bateria'), ('2', 'Guitarra'), ('3', 'Vocal'), ('4', 'Teclado'), ('5', 'Baixo'), ('6', 'Violao'), ('7', 'Som'), ('8', 'Projetor'), ('9', 'Fotofilm'), ('10', 'Live'), ('11', 'Total Midia')], max_length=50, null=True, verbose_name='2ª Função'),
        ),
        migrations.AddField(
            model_name='escala',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
