# Generated by Django 5.1.7 on 2025-03-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_escala_funcao_evento_participantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='funcao_1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='funcao_2',
        ),
        migrations.AlterField(
            model_name='escala',
            name='funcao',
            field=models.CharField(blank=True, choices=[('1', 'Bateria'), ('2', 'Guitarra'), ('3', 'Vocal'), ('4', 'Teclado'), ('5', 'Baixo'), ('6', 'Violao'), ('7', 'Som'), ('8', 'Projetor'), ('9', 'Fotofilm'), ('10', 'Live')], max_length=10, null=True, verbose_name='Função'),
        ),
    ]
