# Generated by Django 5.1.7 on 2025-03-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_usuario_funcao_1_remove_usuario_funcao_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
